# docker-compose up する前にvolumeを作成する
# docker volume create postgres_volume

version: '3'

services:
  fluent_task:
    image: postgres:13.4
    container_name: fluent_task
    expose:
      - '5433'
    ports:
      - '5433:5433'
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    command: -p 5433
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    hostname: postgres
    restart: always
    user: root
volumes:
  postgres_volume:
    external: true
